const int Typeid_BindPriv_add_0 = __COUNTER__;
const int Typeid_Bind_add = __COUNTER__ ;
const int Typeid_Bind_bnot = __COUNTER__ ;
const int Typeid_Bind_booly = __COUNTER__ ;
const int Typeid_Bind_ec = __COUNTER__ ;
const int Typeid_Bind_facc = __COUNTER__ ;
const int Typeid_Bind_mdec = __COUNTER__ ;
const int Typeid_BindPriv_meq_0 = __COUNTER__;
const int Typeid_Bind_meq = __COUNTER__ ;
const int Typeid_BindPriv_mif_0 = __COUNTER__;
const int Typeid_BindPriv_mif_1 = __COUNTER__;
const int Typeid_Bind_mif = __COUNTER__ ;
const int Typeid_Bind_mint = __COUNTER__ ;
const int Typeid_Bind_mis0 = __COUNTER__ ;
const int Typeid_Bind_msuc = __COUNTER__ ;
const int Typeid_BindPriv_mult_0 = __COUNTER__;
const int Typeid_Bind_mult = __COUNTER__ ;
const int Typeid_Bind_pbooly = __COUNTER__ ;
const int Typeid_Bind_pmint = __COUNTER__ ;
const int Typeid_BindPriv_pow_0 = __COUNTER__;
const int Typeid_Bind_pow = __COUNTER__ ;
const int Typeid_Bind_print_false = __COUNTER__ ;
const int Typeid_Bind_print_true = __COUNTER__ ;

struct CustomPriv_add_0;
struct Custom_add;
struct Custom_bnot;
struct Custom_booly;
struct Custom_ec;
struct Custom_facc;
struct Custom_mdec;
struct CustomPriv_meq_0;
struct Custom_meq;
struct CustomPriv_mif_0;
struct CustomPriv_mif_1;
struct Custom_mif;
struct Custom_mint;
struct Custom_mis0;
struct Custom_msuc;
struct CustomPriv_mult_0;
struct Custom_mult;
struct Custom_pbooly;
struct Custom_pmint;
struct CustomPriv_pow_0;
struct Custom_pow;
struct Custom_print_false;
struct Custom_print_true;

int Init_BindPriv_add_0 (ff me_abs);
int Init_Bind_add (ff me_abs);
int Init_Bind_bnot (ff me_abs);
int Init_Bind_booly (ff me_abs);
int Init_Bind_ec (ff me_abs);
int Init_Bind_facc (ff me_abs);
int Init_Bind_mdec (ff me_abs);
int Init_BindPriv_meq_0 (ff me_abs);
int Init_Bind_meq (ff me_abs);
int Init_BindPriv_mif_0 (ff me_abs);
int Init_BindPriv_mif_1 (ff me_abs);
int Init_Bind_mif (ff me_abs);
int Init_Bind_mint (ff me_abs);
int Init_Bind_mis0 (ff me_abs);
int Init_Bind_msuc (ff me_abs);
int Init_BindPriv_mult_0 (ff me_abs);
int Init_Bind_mult (ff me_abs);
int Init_Bind_pbooly (ff me_abs);
int Init_Bind_pmint (ff me_abs);
int Init_BindPriv_pow_0 (ff me_abs);
int Init_Bind_pow (ff me_abs);
int Init_Bind_print_false (ff me_abs);
int Init_Bind_print_true (ff me_abs);

ff Exec_BindPriv_add_0 (ff me_abs, ff __x);
ff Exec_Bind_add (ff me_abs, ff __x);
ff Exec_Bind_bnot (ff me_abs, ff __x);
ff Exec_Bind_booly (ff me_abs, ff __x);
ff Exec_Bind_ec (ff me_abs, ff __x);
ff Exec_Bind_facc (ff me_abs, ff __x);
ff Exec_Bind_mdec (ff me_abs, ff __x);
ff Exec_BindPriv_meq_0 (ff me_abs, ff __x);
ff Exec_Bind_meq (ff me_abs, ff __x);
ff Exec_BindPriv_mif_0 (ff me_abs, ff __x);
ff Exec_BindPriv_mif_1 (ff me_abs, ff __x);
ff Exec_Bind_mif (ff me_abs, ff __x);
ff Exec_Bind_mint (ff me_abs, ff __x);
ff Exec_Bind_mis0 (ff me_abs, ff __x);
ff Exec_Bind_msuc (ff me_abs, ff __x);
ff Exec_BindPriv_mult_0 (ff me_abs, ff __x);
ff Exec_Bind_mult (ff me_abs, ff __x);
ff Exec_Bind_pbooly (ff me_abs, ff __x);
ff Exec_Bind_pmint (ff me_abs, ff __x);
ff Exec_BindPriv_pow_0 (ff me_abs, ff __x);
ff Exec_Bind_pow (ff me_abs, ff __x);
ff Exec_Bind_print_false (ff me_abs, ff __x);
ff Exec_Bind_print_true (ff me_abs, ff __x);

#ifdef DO_CACHING
bool Cache_BindPriv_add_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_add (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_bnot (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_booly (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_ec (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_facc (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mdec (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_meq_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_meq (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_mif_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_mif_1 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mif (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mint (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mis0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_msuc (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_mult_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mult (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_pbooly (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_pmint (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_pow_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_pow (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_print_false (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_print_true (ff me_abs, mapkey_t * ret, recursion_set * set);
#endif
