const int Typeid_BindPriv_add_0 = __COUNTER__;
const int Typeid_Bind_add = __COUNTER__ ;
const int Typeid_Bind_bnot = __COUNTER__ ;
const int Typeid_Bind_booly = __COUNTER__ ;
const int Typeid_Bind_ec = __COUNTER__ ;
const int Typeid_Bind_error = __COUNTER__ ;
const int Typeid_Bind_facc = __COUNTER__ ;
const int Typeid_Bind_mdec = __COUNTER__ ;
const int Typeid_BindPriv_meq_0 = __COUNTER__;
const int Typeid_Bind_meq = __COUNTER__ ;
const int Typeid_BindPriv_mif_0 = __COUNTER__;
const int Typeid_BindPriv_mif_1 = __COUNTER__;
const int Typeid_Bind_mif = __COUNTER__ ;
const int Typeid_Bind_mint = __COUNTER__ ;
const int Typeid_Bind_mis0 = __COUNTER__ ;
const int Typeid_Bind_msuc = __COUNTER__ ;
const int Typeid_BindPriv_mult_0 = __COUNTER__;
const int Typeid_Bind_mult = __COUNTER__ ;
const int Typeid_Bind_pbooly = __COUNTER__ ;
const int Typeid_Bind_pmint = __COUNTER__ ;
const int Typeid_BindPriv_pow_0 = __COUNTER__;
const int Typeid_Bind_pow = __COUNTER__ ;
const int Typeid_Bind_print_false = __COUNTER__ ;
const int Typeid_Bind_print_true = __COUNTER__ ;

struct BindPriv_add_0;
struct Bind_add;
struct Bind_bnot;
struct Bind_booly;
struct Bind_ec;
struct Bind_error;
struct Bind_facc;
struct Bind_mdec;
struct BindPriv_meq_0;
struct Bind_meq;
struct BindPriv_mif_0;
struct BindPriv_mif_1;
struct Bind_mif;
struct Bind_mint;
struct Bind_mis0;
struct Bind_msuc;
struct BindPriv_mult_0;
struct Bind_mult;
struct Bind_pbooly;
struct Bind_pmint;
struct BindPriv_pow_0;
struct Bind_pow;
struct Bind_print_false;
struct Bind_print_true;

int Init_BindPriv_add_0 (struct BindPriv_add_0 *me);
int Init_Bind_add (struct Bind_add *me);
int Init_Bind_bnot (struct Bind_bnot *me);
int Init_Bind_booly (struct Bind_booly *me);
int Init_Bind_ec (struct Bind_ec *me);
int Init_Bind_error (struct Bind_error *me);
int Init_Bind_facc (struct Bind_facc *me);
int Init_Bind_mdec (struct Bind_mdec *me);
int Init_BindPriv_meq_0 (struct BindPriv_meq_0 *me);
int Init_Bind_meq (struct Bind_meq *me);
int Init_BindPriv_mif_0 (struct BindPriv_mif_0 *me);
int Init_BindPriv_mif_1 (struct BindPriv_mif_1 *me);
int Init_Bind_mif (struct Bind_mif *me);
int Init_Bind_mint (struct Bind_mint *me);
int Init_Bind_mis0 (struct Bind_mis0 *me);
int Init_Bind_msuc (struct Bind_msuc *me);
int Init_BindPriv_mult_0 (struct BindPriv_mult_0 *me);
int Init_Bind_mult (struct Bind_mult *me);
int Init_Bind_pbooly (struct Bind_pbooly *me);
int Init_Bind_pmint (struct Bind_pmint *me);
int Init_BindPriv_pow_0 (struct BindPriv_pow_0 *me);
int Init_Bind_pow (struct Bind_pow *me);
int Init_Bind_print_false (struct Bind_print_false *me);
int Init_Bind_print_true (struct Bind_print_true *me);

ff Exec_BindPriv_add_0 (ff me_abs, ff __x);
ff Exec_Bind_add (ff me_abs, ff __x);
ff Exec_Bind_bnot (ff me_abs, ff __x);
ff Exec_Bind_booly (ff me_abs, ff __x);
ff Exec_Bind_ec (ff me_abs, ff __x);
ff Exec_Bind_error (ff me_abs, ff __x);
ff Exec_Bind_facc (ff me_abs, ff __x);
ff Exec_Bind_mdec (ff me_abs, ff __x);
ff Exec_BindPriv_meq_0 (ff me_abs, ff __x);
ff Exec_Bind_meq (ff me_abs, ff __x);
ff Exec_BindPriv_mif_0 (ff me_abs, ff __x);
ff Exec_BindPriv_mif_1 (ff me_abs, ff __x);
ff Exec_Bind_mif (ff me_abs, ff __x);
ff Exec_Bind_mint (ff me_abs, ff __x);
ff Exec_Bind_mis0 (ff me_abs, ff __x);
ff Exec_Bind_msuc (ff me_abs, ff __x);
ff Exec_BindPriv_mult_0 (ff me_abs, ff __x);
ff Exec_Bind_mult (ff me_abs, ff __x);
ff Exec_Bind_pbooly (ff me_abs, ff __x);
ff Exec_Bind_pmint (ff me_abs, ff __x);
ff Exec_BindPriv_pow_0 (ff me_abs, ff __x);
ff Exec_Bind_pow (ff me_abs, ff __x);
ff Exec_Bind_print_false (ff me_abs, ff __x);
ff Exec_Bind_print_true (ff me_abs, ff __x);

#ifdef DO_CACHING
bool Cache_BindPriv_add_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_add (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_bnot (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_booly (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_ec (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_error (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_facc (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mdec (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_meq_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_meq (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_mif_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_mif_1 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mif (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mint (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mis0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_msuc (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_mult_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_mult (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_pbooly (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_pmint (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_BindPriv_pow_0 (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_pow (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_print_false (ff me_abs, mapkey_t * ret, recursion_set * set);
bool Cache_Bind_print_true (ff me_abs, mapkey_t * ret, recursion_set * set);
#endif
